/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretariaVirtualRouteImport } from './routes/secretaria-virtual'
import { Route as PsicopedagogicoRouteImport } from './routes/psicopedagogico'
import { Route as PermanenciaRouteImport } from './routes/permanencia'
import { Route as PeriodoLetivoRouteImport } from './routes/periodo-letivo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OfertaTurmasRouteImport } from './routes/oferta-turmas'
import { Route as MobilidadeRouteImport } from './routes/mobilidade'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as IntegralizacaoRouteImport } from './routes/integralizacao'
import { Route as HistoricoAcademicoRouteImport } from './routes/historico-academico'
import { Route as GestaoPedagogicaRouteImport } from './routes/gestao-pedagogica'
import { Route as GestaoCurricularRouteImport } from './routes/gestao-curricular'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstagiosRouteImport } from './routes/estagios'
import { Route as AtividadesComplementaresRouteImport } from './routes/atividades-complementares'
import { Route as IndexRouteImport } from './routes/index'

const SecretariaVirtualRoute = SecretariaVirtualRouteImport.update({
  id: '/secretaria-virtual',
  path: '/secretaria-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicopedagogicoRoute = PsicopedagogicoRouteImport.update({
  id: '/psicopedagogico',
  path: '/psicopedagogico',
  getParentRoute: () => rootRouteImport,
} as any)
const PermanenciaRoute = PermanenciaRouteImport.update({
  id: '/permanencia',
  path: '/permanencia',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodoLetivoRoute = PeriodoLetivoRouteImport.update({
  id: '/periodo-letivo',
  path: '/periodo-letivo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaTurmasRoute = OfertaTurmasRouteImport.update({
  id: '/oferta-turmas',
  path: '/oferta-turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilidadeRoute = MobilidadeRouteImport.update({
  id: '/mobilidade',
  path: '/mobilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegralizacaoRoute = IntegralizacaoRouteImport.update({
  id: '/integralizacao',
  path: '/integralizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoAcademicoRoute = HistoricoAcademicoRouteImport.update({
  id: '/historico-academico',
  path: '/historico-academico',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoPedagogicaRoute = GestaoPedagogicaRouteImport.update({
  id: '/gestao-pedagogica',
  path: '/gestao-pedagogica',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoCurricularRoute = GestaoCurricularRouteImport.update({
  id: '/gestao-curricular',
  path: '/gestao-curricular',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstagiosRoute = EstagiosRouteImport.update({
  id: '/estagios',
  path: '/estagios',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesComplementaresRoute =
  AtividadesComplementaresRouteImport.update({
    id: '/atividades-complementares',
    path: '/atividades-complementares',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades-complementares': typeof AtividadesComplementaresRoute
  '/estagios': typeof EstagiosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-curricular': typeof GestaoCurricularRoute
  '/gestao-pedagogica': typeof GestaoPedagogicaRoute
  '/historico-academico': typeof HistoricoAcademicoRoute
  '/integralizacao': typeof IntegralizacaoRoute
  '/matricula': typeof MatriculaRoute
  '/mobilidade': typeof MobilidadeRoute
  '/oferta-turmas': typeof OfertaTurmasRoute
  '/perfil': typeof PerfilRoute
  '/periodo-letivo': typeof PeriodoLetivoRoute
  '/permanencia': typeof PermanenciaRoute
  '/psicopedagogico': typeof PsicopedagogicoRoute
  '/secretaria-virtual': typeof SecretariaVirtualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades-complementares': typeof AtividadesComplementaresRoute
  '/estagios': typeof EstagiosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-curricular': typeof GestaoCurricularRoute
  '/gestao-pedagogica': typeof GestaoPedagogicaRoute
  '/historico-academico': typeof HistoricoAcademicoRoute
  '/integralizacao': typeof IntegralizacaoRoute
  '/matricula': typeof MatriculaRoute
  '/mobilidade': typeof MobilidadeRoute
  '/oferta-turmas': typeof OfertaTurmasRoute
  '/perfil': typeof PerfilRoute
  '/periodo-letivo': typeof PeriodoLetivoRoute
  '/permanencia': typeof PermanenciaRoute
  '/psicopedagogico': typeof PsicopedagogicoRoute
  '/secretaria-virtual': typeof SecretariaVirtualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades-complementares': typeof AtividadesComplementaresRoute
  '/estagios': typeof EstagiosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao-curricular': typeof GestaoCurricularRoute
  '/gestao-pedagogica': typeof GestaoPedagogicaRoute
  '/historico-academico': typeof HistoricoAcademicoRoute
  '/integralizacao': typeof IntegralizacaoRoute
  '/matricula': typeof MatriculaRoute
  '/mobilidade': typeof MobilidadeRoute
  '/oferta-turmas': typeof OfertaTurmasRoute
  '/perfil': typeof PerfilRoute
  '/periodo-letivo': typeof PeriodoLetivoRoute
  '/permanencia': typeof PermanenciaRoute
  '/psicopedagogico': typeof PsicopedagogicoRoute
  '/secretaria-virtual': typeof SecretariaVirtualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades-complementares'
    | '/estagios'
    | '/financeiro'
    | '/gestao-curricular'
    | '/gestao-pedagogica'
    | '/historico-academico'
    | '/integralizacao'
    | '/matricula'
    | '/mobilidade'
    | '/oferta-turmas'
    | '/perfil'
    | '/periodo-letivo'
    | '/permanencia'
    | '/psicopedagogico'
    | '/secretaria-virtual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades-complementares'
    | '/estagios'
    | '/financeiro'
    | '/gestao-curricular'
    | '/gestao-pedagogica'
    | '/historico-academico'
    | '/integralizacao'
    | '/matricula'
    | '/mobilidade'
    | '/oferta-turmas'
    | '/perfil'
    | '/periodo-letivo'
    | '/permanencia'
    | '/psicopedagogico'
    | '/secretaria-virtual'
  id:
    | '__root__'
    | '/'
    | '/atividades-complementares'
    | '/estagios'
    | '/financeiro'
    | '/gestao-curricular'
    | '/gestao-pedagogica'
    | '/historico-academico'
    | '/integralizacao'
    | '/matricula'
    | '/mobilidade'
    | '/oferta-turmas'
    | '/perfil'
    | '/periodo-letivo'
    | '/permanencia'
    | '/psicopedagogico'
    | '/secretaria-virtual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesComplementaresRoute: typeof AtividadesComplementaresRoute
  EstagiosRoute: typeof EstagiosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GestaoCurricularRoute: typeof GestaoCurricularRoute
  GestaoPedagogicaRoute: typeof GestaoPedagogicaRoute
  HistoricoAcademicoRoute: typeof HistoricoAcademicoRoute
  IntegralizacaoRoute: typeof IntegralizacaoRoute
  MatriculaRoute: typeof MatriculaRoute
  MobilidadeRoute: typeof MobilidadeRoute
  OfertaTurmasRoute: typeof OfertaTurmasRoute
  PerfilRoute: typeof PerfilRoute
  PeriodoLetivoRoute: typeof PeriodoLetivoRoute
  PermanenciaRoute: typeof PermanenciaRoute
  PsicopedagogicoRoute: typeof PsicopedagogicoRoute
  SecretariaVirtualRoute: typeof SecretariaVirtualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretaria-virtual': {
      id: '/secretaria-virtual'
      path: '/secretaria-virtual'
      fullPath: '/secretaria-virtual'
      preLoaderRoute: typeof SecretariaVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicopedagogico': {
      id: '/psicopedagogico'
      path: '/psicopedagogico'
      fullPath: '/psicopedagogico'
      preLoaderRoute: typeof PsicopedagogicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permanencia': {
      id: '/permanencia'
      path: '/permanencia'
      fullPath: '/permanencia'
      preLoaderRoute: typeof PermanenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodo-letivo': {
      id: '/periodo-letivo'
      path: '/periodo-letivo'
      fullPath: '/periodo-letivo'
      preLoaderRoute: typeof PeriodoLetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta-turmas': {
      id: '/oferta-turmas'
      path: '/oferta-turmas'
      fullPath: '/oferta-turmas'
      preLoaderRoute: typeof OfertaTurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobilidade': {
      id: '/mobilidade'
      path: '/mobilidade'
      fullPath: '/mobilidade'
      preLoaderRoute: typeof MobilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integralizacao': {
      id: '/integralizacao'
      path: '/integralizacao'
      fullPath: '/integralizacao'
      preLoaderRoute: typeof IntegralizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-academico': {
      id: '/historico-academico'
      path: '/historico-academico'
      fullPath: '/historico-academico'
      preLoaderRoute: typeof HistoricoAcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-pedagogica': {
      id: '/gestao-pedagogica'
      path: '/gestao-pedagogica'
      fullPath: '/gestao-pedagogica'
      preLoaderRoute: typeof GestaoPedagogicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-curricular': {
      id: '/gestao-curricular'
      path: '/gestao-curricular'
      fullPath: '/gestao-curricular'
      preLoaderRoute: typeof GestaoCurricularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estagios': {
      id: '/estagios'
      path: '/estagios'
      fullPath: '/estagios'
      preLoaderRoute: typeof EstagiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades-complementares': {
      id: '/atividades-complementares'
      path: '/atividades-complementares'
      fullPath: '/atividades-complementares'
      preLoaderRoute: typeof AtividadesComplementaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesComplementaresRoute: AtividadesComplementaresRoute,
  EstagiosRoute: EstagiosRoute,
  FinanceiroRoute: FinanceiroRoute,
  GestaoCurricularRoute: GestaoCurricularRoute,
  GestaoPedagogicaRoute: GestaoPedagogicaRoute,
  HistoricoAcademicoRoute: HistoricoAcademicoRoute,
  IntegralizacaoRoute: IntegralizacaoRoute,
  MatriculaRoute: MatriculaRoute,
  MobilidadeRoute: MobilidadeRoute,
  OfertaTurmasRoute: OfertaTurmasRoute,
  PerfilRoute: PerfilRoute,
  PeriodoLetivoRoute: PeriodoLetivoRoute,
  PermanenciaRoute: PermanenciaRoute,
  PsicopedagogicoRoute: PsicopedagogicoRoute,
  SecretariaVirtualRoute: SecretariaVirtualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
